import type { CardPrediction } from '../types';

/** Deterministic sample predictions for clarity UI demos / screenshots. */
export const CLARITY_DEMO_PREDICTIONS: CardPrediction[] = [
  {
    id: 1,
    cardId: 'base3-16',
    cardName: 'Aerodactyl',
    setId: 'base3',
    setName: 'Fossil',
    cardNumber: '16',
    rarity: 'Rare Holo',
    imageSmall: 'https://images.pokemontcg.io/base3/16.png',
    imageLarge: 'https://images.pokemontcg.io/base3/16_hires.png',
    currentPrice: 2.41,
    predicted7dLow: 2.2,
    predicted7dMid: 2.55,
    predicted7dHigh: 2.9,
    predicted30dLow: 2.4,
    predicted30dMid: 2.95,
    predicted30dHigh: 3.5,
    predicted90dLow: 2.8,
    predicted90dMid: 3.5,
    predicted90dHigh: 4.4,
    expected7dReturn: 0.058,
    expected30dReturn: 0.224,
    expected90dReturn: 0.45,
    confidenceScore: 62.3,
    riskScore: 31.40975473976649,
    liquidityScore: 48.2,
    category: 'strong_buy',
    suggestedAction: 'Accumulate on dips',
    explanation: 'Mean-reversion after a soft month with improving liquidity.',
    riskFactors: 'Thin print run liquidity on off-condition copies.',
    externalSignals: '[]',
    modelVersion: 'demo',
  },
  {
    id: 2,
    cardId: 'xy2-20',
    cardName: 'Pyroar',
    setId: 'xy2',
    setName: 'Flashfire',
    cardNumber: '20',
    rarity: 'Rare Holo',
    imageSmall: 'https://images.pokemontcg.io/xy2/20.png',
    imageLarge: 'https://images.pokemontcg.io/xy2/20_hires.png',
    currentPrice: 1.12,
    predicted7dLow: 1.0,
    predicted7dMid: 1.18,
    predicted7dHigh: 1.35,
    predicted30dLow: 1.05,
    predicted30dMid: 1.35,
    predicted30dHigh: 1.65,
    predicted90dLow: 1.2,
    predicted90dMid: 1.62,
    predicted90dHigh: 2.05,
    expected7dReturn: 0.054,
    expected30dReturn: 0.205,
    expected90dReturn: 0.446,
    confidenceScore: 58,
    riskScore: 28.1,
    category: 'strong_buy',
    suggestedAction: 'Buy',
    explanation: '',
    riskFactors: 'Low identifiable risk factors.',
    externalSignals: '[]',
    modelVersion: 'demo',
  },
  {
    id: 3,
    cardId: 'xy2-11',
    cardName: 'Charizard',
    setId: 'xy2',
    setName: 'Flashfire',
    cardNumber: '11',
    rarity: 'Rare Holo',
    imageSmall: 'https://images.pokemontcg.io/xy2/11.png',
    imageLarge: 'https://images.pokemontcg.io/xy2/11_hires.png',
    currentPrice: 142.5,
    predicted7dLow: 135,
    predicted7dMid: 148,
    predicted7dHigh: 160,
    predicted30dLow: 130,
    predicted30dMid: 155,
    predicted30dHigh: 175,
    predicted90dLow: 125,
    predicted90dMid: 168,
    predicted90dHigh: 195,
    expected7dReturn: 0.039,
    expected30dReturn: 0.088,
    expected90dReturn: 0.179,
    confidenceScore: 71.8,
    riskScore: 44.6,
    category: 'momentum',
    suggestedAction: 'Hold / trail stop',
    explanation: '',
    riskFactors: 'High absolute dollar risk on pullbacks.',
    externalSignals: '[]',
    modelVersion: 'demo',
  },
  {
    id: 4,
    cardId: 'sv3-199',
    cardName: 'Iono',
    setId: 'sv3',
    setName: 'Obsidian Flames',
    cardNumber: '199',
    rarity: 'Special Illustration Rare',
    imageSmall: 'https://images.pokemontcg.io/sv3/199.png',
    imageLarge: 'https://images.pokemontcg.io/sv3/199_hires.png',
    currentPrice: 48.2,
    predicted7dLow: 44,
    predicted7dMid: 47,
    predicted7dHigh: 51,
    predicted30dLow: 42,
    predicted30dMid: 52,
    predicted30dHigh: 60,
    predicted90dLow: 40,
    predicted90dMid: 58,
    predicted90dHigh: 72,
    expected7dReturn: -0.025,
    expected30dReturn: 0.079,
    expected90dReturn: 0.203,
    confidenceScore: 54.5,
    riskScore: 52.2,
    category: 'recovery',
    suggestedAction: 'Watch for re-entry',
    explanation: '',
    riskFactors: 'SIR premium can compress quickly after hype peaks.',
    externalSignals: '[]',
    modelVersion: 'demo',
  },
];
