import type { CardPrediction, PredictionCategory } from '../types';

type DemoSeed = {
  id: number;
  cardId: string;
  cardName: string;
  setId: string;
  setName: string;
  cardNumber: string;
  rarity: string;
  currentPrice: number;
  expected90dReturn: number;
  confidenceScore: number;
  riskScore: number;
  category: PredictionCategory;
  suggestedAction: string;
};

function buildPrediction(seed: DemoSeed): CardPrediction {
  const { currentPrice: p, expected90dReturn: r90 } = seed;
  const mid90 = +(p * (1 + r90)).toFixed(2);
  const mid30 = +(p * (1 + r90 * 0.45)).toFixed(2);
  const mid7 = +(p * (1 + r90 * 0.12)).toFixed(2);
  return {
    id: seed.id,
    cardId: seed.cardId,
    cardName: seed.cardName,
    setId: seed.setId,
    setName: seed.setName,
    cardNumber: seed.cardNumber,
    rarity: seed.rarity,
    imageSmall: `https://images.pokemontcg.io/${seed.setId}/${seed.cardNumber}.png`,
    imageLarge: `https://images.pokemontcg.io/${seed.setId}/${seed.cardNumber}_hires.png`,
    currentPrice: seed.currentPrice,
    predicted7dLow: +(mid7 * 0.92).toFixed(2),
    predicted7dMid: mid7,
    predicted7dHigh: +(mid7 * 1.08).toFixed(2),
    predicted30dLow: +(mid30 * 0.88).toFixed(2),
    predicted30dMid: mid30,
    predicted30dHigh: +(mid30 * 1.12).toFixed(2),
    predicted90dLow: +(mid90 * 0.82).toFixed(2),
    predicted90dMid: mid90,
    predicted90dHigh: +(mid90 * 1.18).toFixed(2),
    expected7dReturn: +(r90 * 0.12).toFixed(4),
    expected30dReturn: +(r90 * 0.45).toFixed(4),
    expected90dReturn: r90,
    confidenceScore: seed.confidenceScore,
    riskScore: seed.riskScore,
    category: seed.category,
    suggestedAction: seed.suggestedAction,
    explanation: '',
    riskFactors: 'Low identifiable risk factors.',
    externalSignals: '[]',
    modelVersion: 'demo',
  };
}

/** Deterministic sample predictions for clarity UI demos / screenshots. */
const DEMO_SEEDS: DemoSeed[] = [
  {
    id: 1,
    cardId: 'base3-16',
    cardName: 'Aerodactyl',
    setId: 'base3',
    setName: 'Fossil',
    cardNumber: '16',
    rarity: 'Rare Holo',
    currentPrice: 2.41,
    expected90dReturn: 0.45,
    confidenceScore: 62,
    riskScore: 31,
    category: 'strong_buy',
    suggestedAction: 'Accumulate on dips',
  },
  {
    id: 2,
    cardId: 'xy2-20',
    cardName: 'Pyroar',
    setId: 'xy2',
    setName: 'Flashfire',
    cardNumber: '20',
    rarity: 'Rare Holo',
    currentPrice: 1.12,
    expected90dReturn: 0.446,
    confidenceScore: 58,
    riskScore: 28,
    category: 'strong_buy',
    suggestedAction: 'Buy',
  },
  {
    id: 3,
    cardId: 'xy2-11',
    cardName: 'Charizard',
    setId: 'xy2',
    setName: 'Flashfire',
    cardNumber: '11',
    rarity: 'Rare Holo',
    currentPrice: 142.5,
    expected90dReturn: 0.179,
    confidenceScore: 72,
    riskScore: 45,
    category: 'momentum',
    suggestedAction: 'Hold / trail stop',
  },
  {
    id: 4,
    cardId: 'sv3-199',
    cardName: 'Iono',
    setId: 'sv3',
    setName: 'Obsidian Flames',
    cardNumber: '199',
    rarity: 'Special Illustration Rare',
    currentPrice: 48.2,
    expected90dReturn: 0.203,
    confidenceScore: 55,
    riskScore: 52,
    category: 'recovery',
    suggestedAction: 'Watch for re-entry',
  },
  {
    id: 5,
    cardId: 'sv4-223',
    cardName: 'Giratina VSTAR',
    setId: 'sv4',
    setName: 'Paradox Rift',
    cardNumber: '223',
    rarity: 'Special Illustration Rare',
    currentPrice: 86.4,
    expected90dReturn: 0.118,
    confidenceScore: 64,
    riskScore: 41,
    category: 'watch_dip',
    suggestedAction: 'Wait for a pullback',
  },
  {
    id: 6,
    cardId: 'swsh12-215',
    cardName: 'Origin Forme Palkia VSTAR',
    setId: 'swsh12',
    setName: 'Silver Tempest',
    cardNumber: '215',
    rarity: 'Secret Rare',
    currentPrice: 62.0,
    expected90dReturn: 0.092,
    confidenceScore: 61,
    riskScore: 38,
    category: 'momentum',
    suggestedAction: 'Hold',
  },
  {
    id: 7,
    cardId: 'sv3pt5-198',
    cardName: 'Mew ex',
    setId: 'sv3pt5',
    setName: '151',
    cardNumber: '198',
    rarity: 'Special Illustration Rare',
    currentPrice: 74.5,
    expected90dReturn: 0.154,
    confidenceScore: 68,
    riskScore: 36,
    category: 'strong_buy',
    suggestedAction: 'Accumulate',
  },
  {
    id: 8,
    cardId: 'swsh7-215',
    cardName: 'Umbreon VMAX',
    setId: 'swsh7',
    setName: 'Evolving Skies',
    cardNumber: '215',
    rarity: 'Secret Rare',
    currentPrice: 520,
    expected90dReturn: -0.041,
    confidenceScore: 57,
    riskScore: 62,
    category: 'avoid',
    suggestedAction: 'Take profits / avoid chase',
  },
  {
    id: 9,
    cardId: 'sv2-215',
    cardName: 'Gardevoir ex',
    setId: 'sv2',
    setName: 'Paldea Evolved',
    cardNumber: '215',
    rarity: 'Special Illustration Rare',
    currentPrice: 95.0,
    expected90dReturn: 0.067,
    confidenceScore: 59,
    riskScore: 44,
    category: 'watch_dip',
    suggestedAction: 'Buy on dips',
  },
  {
    id: 10,
    cardId: 'swsh9-168',
    cardName: 'Boss Orders',
    setId: 'swsh9',
    setName: 'Brilliant Stars',
    cardNumber: '168',
    rarity: 'Trainer Gallery',
    currentPrice: 18.5,
    expected90dReturn: 0.031,
    confidenceScore: 48,
    riskScore: 33,
    category: 'stagnant',
    suggestedAction: 'Low priority',
  },
  {
    id: 11,
    cardId: 'sv5-161',
    cardName: 'Iron Valiant ex',
    setId: 'sv5',
    setName: 'Temporal Forces',
    cardNumber: '161',
    rarity: 'Ultra Rare',
    currentPrice: 12.8,
    expected90dReturn: -0.086,
    confidenceScore: 52,
    riskScore: 55,
    category: 'downtrend',
    suggestedAction: 'Reduce exposure',
  },
  {
    id: 12,
    cardId: 'swsh11-TG14',
    cardName: 'Single Strike Urshifu VMAX',
    setId: 'swsh11tg',
    setName: 'Lost Origin Trainer Gallery',
    cardNumber: 'TG14',
    rarity: 'Trainer Gallery',
    currentPrice: 24.0,
    expected90dReturn: 0.124,
    confidenceScore: 56,
    riskScore: 40,
    category: 'recovery',
    suggestedAction: 'Watch for bounce',
  },
  {
    id: 13,
    cardId: 'sv6-163',
    cardName: 'Pikachu ex',
    setId: 'sv6',
    setName: 'Twilight Masquerade',
    cardNumber: '163',
    rarity: 'Special Illustration Rare',
    currentPrice: 38.0,
    expected90dReturn: 0.211,
    confidenceScore: 66,
    riskScore: 35,
    category: 'strong_buy',
    suggestedAction: 'Buy',
  },
  {
    id: 14,
    cardId: 'swsh8-183',
    cardName: 'Rayquaza VMAX',
    setId: 'swsh8',
    setName: 'Fusion Strike',
    cardNumber: '183',
    rarity: 'Ultra Rare',
    currentPrice: 28.4,
    expected90dReturn: 0.048,
    confidenceScore: 51,
    riskScore: 39,
    category: 'stagnant',
    suggestedAction: 'Hold if owned',
  },
  {
    id: 15,
    cardId: 'sv1-238',
    cardName: 'Miraidon ex',
    setId: 'sv1',
    setName: 'Scarlet & Violet',
    cardNumber: '238',
    rarity: 'Special Illustration Rare',
    currentPrice: 41.2,
    expected90dReturn: 0.137,
    confidenceScore: 63,
    riskScore: 37,
    category: 'momentum',
    suggestedAction: 'Ride the trend',
  },
  {
    id: 16,
    cardId: 'xy12-11',
    cardName: 'M Charizard-EX',
    setId: 'xy12',
    setName: 'Evolutions',
    cardNumber: '11',
    rarity: 'Rare Holo EX',
    currentPrice: 55.0,
    expected90dReturn: 0.089,
    confidenceScore: 60,
    riskScore: 42,
    category: 'watch_dip',
    suggestedAction: 'Buy the dip',
  },
];

export const CLARITY_DEMO_PREDICTIONS: CardPrediction[] = DEMO_SEEDS.map(buildPrediction);
